### ISSUE TITLE
Support for bevy 0.14

### ISSUE THREAD

**Issue by shanecelis** [makspll/bevy_mod_scripting#124]
I tried doing this myself. At first it didn't seem like it would be much work. However, once I got to the autogenerated code, I got lost. Is there any documentation or guidance for how you go about updating your bevy version? I'd be happy to attempt a PR.

**Comment by makspll** [comment]
Hi, I will be looking at doing more work on this repo soon :) 

I haven't checked the extent of changes necessary for this update, but on the happy path migrating code-gen just entails running the code gen scripts. If the minimum supported rust version has changed this will be more complicated especially since we now hook into the compiler directly (and we might require looking through the changes to the compiler + reconciling them with the code gen).

The good news is soon bevy will be supporting function/method reflection, which is going to reduce the need for code gen (probably within a release or two)

**Comment by shanecelis** [comment]
That would be great! I've got a branch that contains some of the easy [bevy-0.14 grunt work](https://github.com/shanecelis/bevy_mod_scripting/tree/bevy-0.14). The last commit there can probably be dropped.

You're very welcome. I think this crate is a huge asset to the bevy community so THANK YOU!

**Comment by makspll** [comment]
Just bumped `bevy-console` and looking at the bevy migration notes, recursive reflect type registration might cause some issues, i.e. we might have to register all the primitive types, I will begin migrating off of your branch @shanecelis and see if there's anything problematic :)

**Comment by makspll** [comment]
I've just gotten 0.14 working on the linked PR :)
