### ISSUE TITLE
Possible to load .dll files?

### ISSUE THREAD

**Issue by Semihazah** [makspll/bevy_mod_scripting#13]
I realize that the environment is likely in sandbox mode, but is it possible? I'm trying to run ([narrator ](https://github.com/astrochili/narrator) which requires [lpeg](https://luarocks.org/modules/gvvaughan/lpeg) but it doesn't seem to search for dlls.

**Comment by makspll** [comment]
Hi, 
I remember trying to import some other lua files from the scripts folder, and if i remember correctly that might work, but i am not sure about luarocks packages,

I would post an issue directly on rlua's repo since I basically just host the scripts directly with their library, so if it's possible there it's possible here!

**Comment by coderedart** [comment]
with mlua, I can vouch that loading shared libraries works. I made a dll (.so on linux) with rust (using C abi) and successfully `require`d it with a mlua script. 

the lua environment technically can't be sandboxed anyway :D there's a lot of unsafe things happening behind the scenes between luajit + rust + lua combo. it is sort of possible with luau backend (roblox version of lua) of mlua as that is explicitly designed for sandboxing.  

maybe with a wasm based lua vm or https://github.com/danii/hematita we can get proper safe sandboxing in future.

you can use (and also create) luarocks packages, but you need to manage them externally and add the path + cpath of luarocks install target location to the mlua vm.

**Comment by makspll** [comment]
I am planning on swapping to mlua anyway, or rather tealr for documentation generation features, so if rlua does not allow for external modules this won't be a problem for too long. I'll investigate this once i am done working on the bevy script facing API!

**Comment by lenscas** [comment]
both mlua and rlua don't allow loading C libraries by default. They also don't allow loading the debug module by default.

You can enable both of them to allow this, but this requires `unsafe` functions to create the lua instance as both C libraries and the debug module can result in UB due to circumventing Rust's borrow rules and/or messing with state that mlua and rlua depend on.

So, in both cases it is less about sandboxing, but more as an attempt to make sure that no UB happens through their safe api. I believe there is an issue on rlua about it, questioning if this design is not more harmful than useful.

**Comment by makspll** [comment]
Hmm in this case I might put that functionality behind a feature to make it opt-in. Thanks for the info @lenscas!

**Comment by lenscas** [comment]
May I suggest another name for that feature? Considering that enabling it presumably also enables the debug module. It is probably also good if the feature name itself makes it clear that ub can happen if it is enabled.

`unsafe_lua_instance` at least makes the fact that it uses unsafe clear but stays a bit vague. Though that might be a good thing to hopefully get people to read the docs so they know why it is unsafe?

**Comment by makspll** [comment]
That's probably a good idea, i will name it `unsafe_lua_modules`  though to imply clearly what *functionality* is enabled with the feature
