### ISSUE TITLE
Task Scheduler

### ISSUE THREAD

**Issue by katk0smos** [makspll/bevy_mod_scripting#32]
So this is more of a general feature request/enhancement (also a question), but something that would be extremely useful in my use cases would be having a task scheduler so that scripts could, for example, yield back to the engine for a specified duration (like a `sleep` function). This could also potentially be used for calling callback functions bound to specific events through functions, rather than having specific hook functions.

An example of this might look like this:
```lua
-- another benefit of this is having multiple callbacks defined per script
physics_stepped_event:bind(function()
  -- do something
  sleep(5) -- sleep for 5 seconds
  -- do something else
end)
```
Rather than the current hook-based system:
```lua
-- it's a hook so it can only be defined once per script
function physics_stepped_event()
  -- do something
  -- no idea how you'd wait here, maybe call a function and pass the name of another hook to call as well as the time to sleep?
end
```

I do know this isn't currently possible with the current language implementations, but could something like this be implemented on top of the existing traits? I do know the current system _probably_ works better under Bevy's ECS system, but for me the benefits from having this outweighs the extra work I'd have to do to create the necessary APIs.

It's something that would be extremely useful for my projects, and would be something I would consider implementing myself as well (and of course I'd be willing to consider submitting a PR if you think it'd be a worthy addition). I just don't know enough about how the code is structured to know if I could implement this on top of it or not.

**Comment by katk0smos** [comment]
I submitted a PR (#34) that allows for asynchronous functions, which would theoretically allow the scripts to yield in the background. I believe this is required to implement the task scheduler properly. The only issue is that the values returned by `mlua` are locked to the lifetime of the `Lua` struct, and cannot be passed between threads.

I don't know if you happen to know a solution to this issue, or if bevy just isn't a suitable choice for what I'm trying to do. Essentially I need a way of storing all of the Lua contexts and return values on a single thread. I did have the idea of just spawning a background thread that would own everything, but passing messages back and forth seems somewhat messy and I feel like it would defeat the purpose of this crate.

**Comment by makspll** [comment]
@katk0smos, are you trying to keep a hold of and pass around mlua threads? The way Bevy works, resources/components must be `'static` i.e. have no lifetimes attached.

Currently all the scripts added via this plugin are stored in [`ScriptContexts`](https://github.com/makspll/bevy_mod_scripting/blob/781754a7e43730885e58fa89b1f911ae800bf985/bevy_mod_scripting_core/src/hosts.rs#L259) inside of Mutexes. I am not sure what you mean by storing all of them on a single thread, when the Bevy game loop runs, systems are parallelized and run in their own threads, for this plugin, because the [handler systems](https://github.com/makspll/bevy_mod_scripting/blob/781754a7e43730885e58fa89b1f911ae800bf985/bevy_mod_scripting_core/src/systems.rs#L153)  are exclusive, they have sole control over the contexts when they run, i.e. all of these contexts are controlled by a single thread and events are handled in sequence.  The plugin does not dictate what the ScriptHost's do with the events, and the hosts can do whatever they want in the [`handle_events`](https://github.com/makspll/bevy_mod_scripting/blob/781754a7e43730885e58fa89b1f911ae800bf985/languages/bevy_mod_scripting_lua/src/lib.rs#L139) hook. 

I am guessing you're trying to get `Thread` as a return value from the scripts? You won't be able to store that in a resource or anything, but I believe you should be fine manipulating those threads within the context of a single `handle_events` hook (although I am not very sure, I've not tried anything like this).

But then I am just guessing, it's a bit hard for me to imagine what you're trying to do (some examples would help), may I ask why coroutines don't suit your use case?

**Comment by katk0smos** [comment]
I think Bevy just may not be designed for what I'm attempting to do. I was looking to create a Lua API similar to that used in Roblox,

Since I don't believe Bevy will work for what I'm attempting to do with this, I'm just going to close this issue. Thank you for all the help!

**Comment by makspll** [comment]
@katk0smos looking at the roblox task scheduling, I'd say you'd be able to get the delay mechanics working, i.e. if all you want to do is yield an event call, put it in some queue then immediately after all normal events are handled handle that queue, that should be possible:
say you have:
```lua
function EventA()
return my_function_or_coruotine
end
```
1. `EventA()` is called
2. returned function is put on queue of "delayed" events
3. once all normal events are handled, call all of the delayed functions/coroutines untill the queue is empty

This sort of behaviour should be possible entirely within the `handle_events` hook, anything that requires tasks to be delayed through another frame I would just handle with coroutines as I've shown above
