### ISSUE TITLE
Bevy 0.10 compatibility

### ISSUE THREAD

**Issue by ChrisPWill** [makspll/bevy_mod_scripting#45]
Hey there, love the crate. Bevy 0.10 does away with stages in favour of system sets - is there any plan to update this library to support this?

**Comment by awestlake87** [comment]
FWIW, I'm not a maintainer of this crate, but I've been experimenting with adding Teal/Lua scripting to a Bevy 0.10 project of mine.

It took a decent amount of effort to switch this project over, and in the process I fixed a couple of bugs with the game_of_life_lua example (turns out it wasn't working on master, at least not on Windows 11 anyway). 

I won't claim it's bug-free, but Lua 5.4 / Teal scripting is functional on my Bevy 0.10 fork right now, so feel free to check it out if you're impatient like me: https://github.com/awestlake87/bevy_mod_scripting

Just so you know:
- I haven't touched Rhai at all yet, so my fork is probably still broken if you enable the Rhai features
- It's bare-bones, meaning it compiles but I haven't updated any of the docs or taken the time to tidy  up what I wrote for it
- The game_of_life fix involves a small patch to the tealr project so that's why it's pointing to another fork of mine. Doesn't matter if you want plain Lua, but I like types so I figured I'd give Teal a try. 
  - It'll work without you having to change anything, but if this turns into a PR we'd probably have to open a PR over there too.

**Comment by makspll** [comment]
Hey all!

@ChrisPWill thanks and yes I will be updating as soon as I can!

@awestlake87 thanks so much, these sorts of contributions help out a tonne! Some great catches there, feel free to start a PR, I can work off of it to make sure your improvements get credited back to you!

**Comment by awestlake87** [comment]
@makspll sure! I created #46 for it and listed out the remaining tasks as I see it. I also noticed that you updated bevy-console to 0.7, so I updated the console_integration_lua example.

**Comment by passeride** [comment]
Any more progress on this?

**Comment by makspll** [comment]
This should be covered by #47. Apologies for the long delay, I am looking for maintainers, to reduce the delay in the future if any of you are interested!

**Comment by makspll** [comment]
I've managed to hotfix this directly on our side, 0.3.0 just got released, should be good to go!
